### ISSUE TITLE
conflicting key bindings

### ISSUE THREAD

**Issue by wintermute42** [geapi/atomJ#1]
Hi,
thanks for starting this project. Good idea.
I just started using atom and will be using it as a secondary code editor, so it should adjust to what I'm used to with IntelliJ, not the other way around. I included the atomJ keymap and noticed that some shortcuts conflict with other atom key bindings. If I find time I'll try to solve the issue by re-assigning the other atom key bindings. But before I do that, maybe you already did it? If so, would you mind committing the new version?

**Comment by geapi** [comment]
You can unset bindings if they conflict. I haven't run into that.
